# Generated by Django 5.0.6 on 2024-07-04 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter_lev', models.CharField(choices=[('4A', 'winter'), ('2A', 'spring'), ('1A', 'summer'), ('3A', 'autumn')], default='4A', max_length=2)),
                ('spring_lev', models.CharField(choices=[('4A', 'winter'), ('2A', 'spring'), ('1A', 'summer'), ('3A', 'autumn')], default='4A', max_length=2)),
                ('summer_lev', models.CharField(choices=[('4A', 'winter'), ('2A', 'spring'), ('1A', 'summer'), ('3A', 'autumn')], default='4A', max_length=2)),
                ('autumn_lev', models.CharField(choices=[('4A', 'winter'), ('2A', 'spring'), ('1A', 'summer'), ('3A', 'autumn')], default='4A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('patronymic', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('other_titles', models.CharField(max_length=128)),
                ('connect', models.CharField(max_length=128)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NW', 'Создан'), ('PN', 'На проверке'), ('AC', 'Принят'), ('RJ', 'Отклонен')], default='NW', max_length=2)),
                ('coord_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mount.coords')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mount.level')),
                ('tourist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mount.users')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=128)),
                ('pereval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mount.pereval')),
            ],
        ),
    ]
