# Generated by Django 5.0.6 on 2024-07-12 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter_lev', models.CharField(choices=[('1A', '1A'), ('1Б', '1Б'), ('2A', '2A'), ('2Б', '2Б'), ('3A', '3A'), ('3Б', '3Б')], max_length=2)),
                ('spring_lev', models.CharField(choices=[('1A', '1A'), ('1Б', '1Б'), ('2A', '2A'), ('2Б', '2Б'), ('3A', '3A'), ('3Б', '3Б')], max_length=2)),
                ('summer_lev', models.CharField(choices=[('1A', '1A'), ('1Б', '1Б'), ('2A', '2A'), ('2Б', '2Б'), ('3A', '3A'), ('3Б', '3Б')], max_length=2)),
                ('autumn_lev', models.CharField(choices=[('1A', '1A'), ('1Б', '1Б'), ('2A', '2A'), ('2Б', '2Б'), ('3A', '3A'), ('3Б', '3Б')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('patronymic', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('other_titles', models.CharField(max_length=128)),
                ('connect', models.CharField(blank=True, max_length=128)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'new'), ('PENDING', 'pending'), ('ACCEPTED', 'accepted'), ('REJECTED', 'rejected')], default='NEW', max_length=8)),
                ('coord_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mount.coords')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mount.level')),
                ('tourist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mount.users')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=100)),
                ('pereval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mount.pereval')),
            ],
        ),
    ]
